import { TierId } from "./moduleFiles";

export default function buildSeedFile(
  adminName: string,
  adminEmail: string,
  adminPassword: string,
  tier: TierId,
): string {
  return `// prisma/seed.ts — Auto-generated by HotelGen
import { prisma } from "@/database/db";
import bcrypt from "bcryptjs";


async function main() {
  console.log(" Seeding database...");

  // ── Admin User ──────────────────────────────────────────────
  const adminPasswordHash = await bcrypt.hash("${adminPassword}", 10);

  const admin = await prisma.user.upsert({
    where: { email: "${adminEmail}" },
    update: {},
    create: {
      name: "${adminName}",
      email: "${adminEmail}",
      password: adminPasswordHash,
      role: "ADMIN",
      isVerified: true,
      isActive: true,
    },
  });

  console.log(\` Admin created: \${admin.email}\`);
  console.log(\` Seeding complete (\${"${tier}"} tier)\`);
  console.log(" Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(" Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
`;
}
