import { TierId } from "./moduleFiles";

export default function buildSeedFile(
  adminName: string,
  adminEmail: string,
  adminPassword: string,
  tier: TierId,
): string {
  const isBasic = tier === "basic";
  const hasStaff = tier !== "basic";

  return `// prisma/seed.ts — Auto-generated by HotelGen
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // ── Admin User ──────────────────────────────────────────────
  const adminPasswordHash = await bcrypt.hash("${adminPassword}", 10);

  const admin = await prisma.user.upsert({
    where: { email: "${adminEmail}" },
    update: {},
    create: {
      name: "${adminName}",
      email: "${adminEmail}",
      password: adminPasswordHash,
      role: "ADMIN",
      isVerified: true,
      isActive: true,
    },
  });

  console.log(\`✅ Admin created: \${admin.email}\`);

${isBasic ? `
  // ── Basic Tier: No staff/customer seeding ──────────────────
  console.log("✅ Seeding complete (Basic tier)");
` : `
  // ── Staff User ──────────────────────────────────────────────
  const staffPasswordHash = await bcrypt.hash("staff123", 10);
  
  const staff = await prisma.user.upsert({
    where: { email: "staff@hotel.com" },
    update: {},
    create: {
      name: "Staff User",
      email: "staff@hotel.com",
      password: staffPasswordHash,
      role: "STAFF",
      isVerified: true,
      isActive: true,
    },
  });
  console.log(\`✅ Staff created: \${staff.email}\`);

  // ── Customer User ────────────────────────────────────────────
  const customerPasswordHash = await bcrypt.hash("customer123", 10);
  
  const customer = await prisma.user.upsert({
    where: { email: "customer@hotel.com" },
    update: {},
    create: {
      name: "Customer User",
      email: "customer@hotel.com",
      password: customerPasswordHash,
      role: "CUSTOMER",
      isVerified: true,
      isActive: true,
    },
  });
  console.log(\`✅ Customer created: \${customer.email}\`);

  // ── Staff Profile (if staff module exists) ──────────────────
  // (Optional: Add basic department and shift configs)

  console.log("✅ Seeding complete (${tier} tier)");
`}

  console.log("🎉 Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
`;
}